services:
  news_factory:
    container_name: news_factory_server
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    ports:
      - "8036:8036"
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      CONFIG_PATH: /usr/src/app/config.json
    volumes:
      - ..:/usr/src/app
      - /path/to/your/project/data:/usr/src/app/data
      - ../config_docker.json:/usr/src/app/config.json
    command: ["python", "run.py", "--config", "/usr/src/app/config.json"]
